//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraduateDeveloperAssignment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public long TransactionID { get; set; }
        public decimal Amount { get; set; }
        public short TransactionTypeId { get; set; }
        public int ClientID { get; set; }
        public string Comment { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual TransactionType TransactionType { get; set; }
    }
}
